### ISSUE TITLE
Doc validator/client split

### ISSUE THREAD

**Issue by MadelineMurray** [ConsenSys/doc.teku#154]
Still under development currently.

**Comment by ajsutton** [comment]
This should be ready to doc now.  Nothing special needed on the beacon chain side, there's a `validator-client` subcommand to run the validator.

Most important point is that the validator keys should only be provided to the Validator Client - definitely never ever pass the validator keys as CLI args to both the beacon node and the Validator Client or it will run the validators in both and get you slashed.
