### ISSUE TITLE
Document Teku System Requirements

### ISSUE THREAD

**Issue by bgravenorst** [ConsenSys/doc.teku#16]

**Comment by MadelineMurray** [comment]
From @ajsutton: 

> I think it is a good idea to mention that -Xmx can be used to tweak the jvm memory allocation with a note that it may be particularly useful when Teku is the only thing running on the box (ie in docker or dedicated VMs).

> At this point we can’t provide any recommended amounts of memory - it’s just changing too fast.  

> The other useful point would be that the metrics indicate how much on and off heap memory is used and the time spent doing GC which is the data you need to effectively tune the memory settings.

**Comment by rolfyone** [comment]
https://github.com/ConsenSys/teku/issues/3335

teku will attempt to grow its heap as much as it can, but on systems with less memory it can be particularly handy to limit the amount of heapspace java can consume.

if teku exits with `java.lang.OutOfMemoryError: Java heap space` then limiting heap space may be particularly useful.

From searching discord, if your computer has 8GB RAM, then `-Xmx=5632m` can be a good starting point for the heap, if nothing else is consuming significant memory.

The actual amount of memory required would depend partially on the network - the pyrmont network does appear to require more as a minimum than medalla network did (except when the network wasn't finalizing, which did mean teku needed more memory to run)

Currently the best guidance is probably only that teku is requiring about 2GB outside of heap space, so limiting the heap to MEM-2G is a good starting point (6 gig machine = 4G heap), but it's still dependent on so many factors.

There have been many times of late that 2G heap wasn't sufficient, so it's difficult to see teku running successfully on a network if the machine has less than 6G total memory available...
