### ISSUE TITLE
Remove Teku's validator generate/register functionality

### ISSUE THREAD

**Issue by bgravenorst** [ConsenSys/doc.teku#170]
See https://github.com/PegaSysEng/teku/pull/2899

**Comment by mbaxter** [comment]
Heads up - we're talking about potentially just deprecating these for some amount of time before completely removing them: https://github.com/PegaSysEng/teku/pull/2919

**Comment by ajsutton** [comment]
I'd still remove all trace of them from the docs immediately though.
