### ISSUE TITLE
Document weak subjectivity options

### ISSUE THREAD

**Issue by mbaxter** [ConsenSys/doc.teku#181]
Document weak subjectivity options. See: https://github.com/ConsenSys/teku/pull/2936

We probably also want a brief explanation of the weak subjectivity concept and when these arguments would be used.  Something along the lines of: 

> In the Ethereum 2.0 proof-of-stake system, nodes that are offline for a long period of time may not be able to objectively determine the correct chain to follow.  This system is "weakly subjective" because a "subjective" (chosen by the user) checkpoint can be be supplied in this case in order to guarantee safety.  The weak subjectivity checkpoint is a recent finalized checkpoint on the correct chain.  It protects the node from long-range attacks by malicious actors. 

There is currently no official mechanism to distribute weak subjectivity checkpoints, when a mechanism is determined, we'll want to add documentation on where users can find values for the weak-subjectivity-checkpoint argument.

Additional options related to weak-subjectivity are in development as well: users will soon be able to supply a full beacon state from which to sync in lieu of a weak-subjectivity checkpoint.

**Comment by mbaxter** [comment]
Etherscan is now serving WS checkpoint info, currently at: https://beaconscan.com/ws_checkpoint, which you can navigate to from the home page:
<img width="1410" alt="Screen Shot 2020-11-10 at 11 28 39 AM" src="https://user-images.githubusercontent.com/658601/98702402-52480080-2348-11eb-8c56-a56c7594a5f5.png">

**Comment by mbaxter** [comment]
@MadelineMurray - should I create another ticket to add information on retrieving the weak-subjectivity checkpoint (last comment I posted)? ^

**Comment by bgravenorst** [comment]
@mbaxter - I raised this issue to capture this work.

https://github.com/ConsenSys/doc.teku/issues/205
