### ISSUE TITLE
Update p2p-peer-lower-bound and p2p-peer-upper-bound

### ISSUE THREAD

**Issue by ajsutton** [ConsenSys/doc.teku#210]
https://docs.teku.consensys.net/en/latest/Reference/CLI/CLI-Syntax/#p2p-peer-lower-bound lists the default peer bounds as 20-30 but these values have since been updated to 64-74.

**Comment by bgravenorst** [comment]
This has been fixed in https://github.com/ConsenSys/doc.teku/commit/359b135d900ee876ac172c691f60336815958ae7#diff-67880e21f8ea3621d48fe26b9777a1d9d28b02c2d2d7bd15d2663b919cabb57f
