### ISSUE TITLE
Document the voluntary-exit subcommand

### ISSUE THREAD

**Issue by bgravenorst** [ConsenSys/doc.teku#215]
Teku allows you to the run the `voluntary-exit` subcommand to exit a validator.

See: https://github.com/ConsenSys/teku/issues/3273

**Comment by benjaminion** [comment]
Here are some notes in case its useful.

From @ajsutton [on discord]( https://discord.com/channels/697535391594446898/697539289042649190/778031361696464927)
> Teku now has a subcommand to make this simple for you.  `teku voluntary-exit --beacon-node-api-endpoint http://localhost:5051 <validator-keys-options>` That assumes your beacon node is running on the same system and has `--rest-api-enabled`.  If the node is on a different system or a different port you may need to adjust the URL.  The `<validator-keys-options>` specifies the keys for the validators you want to exit.  If you want to exit all your validators just specify the same options you give to Teku. You can even just specify the same config file as you use for Teku with `teku voluntary-exit --config-file`.
`teku voluntary-exit --help` will give you all the available options.

I did this on Medalla
```
teku voluntary-exit --config-file teku.yaml --epoch 24500
```

You can check the node's pending exit queue with
```
curl -X GET "http://albert:5051/eth/v1/beacon/pool/voluntary_exits" -H "accept: application/json"
```
