### ISSUE TITLE
Example on REST-API returns 404

### ISSUE THREAD

**Issue by cdivitotawela** [ConsenSys/doc.teku#223]
As Teku user I refer the [rest api documentation](https://docs.teku.consensys.net/en/latest/Reference/Rest_API/Rest/). I used an example on this page `curl -X GET "http://localhost:5051/beacon/committees?epoch=2"` but it returns 404 error.

Reproduce steps:
- Start Teku with REST API enabled
- Verify teku started
- Run curl command and it returns 404

**Comment by NicolasMassart** [comment]
Need to check with team but I think the API changed since we wrote this and the correct method is now [`/eth/v1/beacon/states/{state_id}/committees`](https://consensys.github.io/teku/#operation/getEthV1BeaconStatesWithState_idCommittees) using `epoch` parameter in the body payload.

**Comment by ajsutton** [comment]
Correct except `epoch` is still a query param.  Probably not the API I'd pick as an example though - I'd probably go with `/eth/v1/node/identity` which gives some basic info about the node and is a lot easier to understand.

**Comment by NicolasMassart** [comment]
Yes that was my though too as it seems a bit complicated for a first example. We will update the doc. Thanks for the infos.

**Comment by rolfyone** [comment]
`/eth/v1/beacon/genesis` is also a nice one depending on what you're looking for...

**Comment by NicolasMassart** [comment]
A simple one just to show how to make an API call. And one that doesn't provide too long result so that's easy to display ;)
