### ISSUE TITLE
Improvement regarding --eth1-endpoint description

### ISSUE THREAD

**Issue by 3eph1r0th** [ConsenSys/doc.teku#228]
`--eth1-endpoint` description

If not specified, then provide an initial state using the --initial-state option, or start Teku from an existing database using --data-path, which provides the initial state to work from.

`--initial-state` description 

This option does not need to be specified if the genesis state is provided by the network specified using the --network option.

`--network` description

Predefined networks can provide defaults such the initial state of the network, bootnodes, and the address of the Ethereum 1.0 deposit contract.

------------------------------------------------------------------------------------

It would be great to specify that `--eth1-endpoint` is a mandatory setting if you run a validator node. Right now, it gives false expectations that everything will work even without this option. Also it will be a good idea not to allow connection to beacon node if `--eth1-endpoint` is not specified.

**Comment by MadelineMurray** [comment]
@3eph1r0th - thanks for taking the time to raise. We'll look at updating the doc to make this clearer.
