### ISSUE TITLE
Load the deposit contract from constants if it hasn't been set

### ISSUE THREAD

**Issue by bgravenorst** [ConsenSys/doc.teku#265]
Deposit contract address can be loaded from constants, basically if the deposit contract isn't specified in the network configuration, it will be loaded from constants now. previously the doc stated it could be loaded from --initial-state or --network, which should continue to hold true, but now if it's not defined on startup by the network, then it will load from the defined constants.

See https://github.com/ConsenSys/teku/pull/3724

**Comment by alexandratran** [comment]
The --network option (https://docs.teku.consensys.net/en/latest/Reference/CLI/CLI-Syntax/#network) already states that a configuration (constants) file or directory can be specified, and that the file or network name specified can provide a default deposit contract.
