### ISSUE TITLE
Add information about password file encoding

### ISSUE THREAD

**Issue by remyroy** [ConsenSys/doc.teku#269]
From my understanding, the password file encoding should be UTF-8. That important information is currently not provided in the documentation. It should probably be added at least in https://docs.teku.consensys.net/en/latest/HowTo/Get-Started/Connect/Connect-To-Testnet/#create-a-password-file-for-each-validator-key

**Comment by remyroy** [comment]
and in https://docs.teku.consensys.net/en/latest/HowTo/Get-Started/Connect/Connect-To-Mainnet/#create-a-password-file-for-each-validator-key

**Comment by ajsutton** [comment]
Confirming that the password file is indeed UTF-8 and we use the EIP2335 normalisation rules (https://eips.ethereum.org/EIPS/eip-2335#password-requirements) which should match what everyone else is doing..
