### ISSUE TITLE
Document how to migrate the Teku database

### ISSUE THREAD

**Issue by bgravenorst** [ConsenSys/doc.teku#296]
Document the `migrate-database` subcommand and how to use it to migrate the Teku database

See: https://github.com/ConsenSys/teku/pull/4110#issuecomment-868177573

Confirm whether we should keep the existing instructions [here](https://docs.teku.pegasys.tech/en/latest/HowTo/Migrate-Database/), or use the subcommand instead.

**Comment by ajsutton** [comment]
I'd suggest for instances using `prune` storage mode (the default) using a checkpoint sync is probably the easiest way to go still and will have less downtime.  The migration tool is aimed at people using `archive` mode.
