### ISSUE TITLE
Teku documentation shows an option that may not be available for validator-client

### ISSUE THREAD

**Issue by gethwethreth** [ConsenSys/doc.teku#387]
Visit the below link and you will see a section for [initial-state](https://docs.teku.consensys.net/en/latest/Reference/CLI/Subcommands/Validator-Client/#initial-state) which is not even a valid option for validator-client

https://docs.teku.consensys.net/en/latest/Reference/CLI/Subcommands/Validator-Client/

`teku validator-client --help` in CLI does not show initial-state

**Comment by rolandtyler** [comment]
<img width="591" alt="vc initial-state" src="https://user-images.githubusercontent.com/88206508/185473813-d7b01fe4-c49f-442f-8c3c-f401cd55b92e.png">
Hi @gethwethreth,  `initial-state` shows up just under `h, --help` when using `teku validator-client --help`. I've attached the screen shot here.  Please let me know if you need any additional help.  Thanks!

**Comment by ajsutton** [comment]
Going to reopen this one. I'm not sure what version of Teku you're using but `--initial-state` isn't listed in help for the latest version of teku. I think it was mistakenly present in earlier versions though it was ignored.  If we have `--eth1-deposit-contract-address` listed we should remove it too as it falls into the same category.
