### ISSUE TITLE
Document voluntary exiting validators with public key. 

### ISSUE THREAD

**Issue by rolandtyler** [ConsenSys/doc.teku#398]
Use `voluntary-exit` subcommand for voluntary exit of validators added via REST API.
The voluntary-exit subcommand can be used with a validator public keys filter option to support the validators added via REST API: `--public-keys-filter`.
Example: `teku voluntary-exit --beacon-node-api-endpoint=<ENDPOINT>[,<ENDPOINT>...]... --data-validator-path=<PATH> --include-keymanager-keys=<BOOLEAN> --validator-keys=<KEY_DIR>:<PASS_DIR> | <KEY_FILE>:<PASS_FILE> --public-keys-filter=<PUBKEY>[,<PUBKEY>...]...`
To include validator keys managed via keymanager APIs, the option `--include-keymanager-keys` could be set to `true` (The default value is set to `false`).

See https://github.com/ConsenSys/teku/pull/6250

**Comment by alexandratran** [comment]
Already fixed by #401
