### ISSUE TITLE
Broken link to CL client architecture on docs.ethhub.io (site dead)

### ISSUE THREAD

**Issue by NicolasMassart** [ConsenSys/doc.teku#417]
## Describe the bug

Link to https://docs.ethhub.io/ethereum-roadmap/ethereum-2.0/eth-2.0-client-architecture/ on ./docs/Concepts/ArchitectureOverview.md is broken. Site no longer exists.

- [ ] Missing content
- [x] Outdated content
- [ ] Wrong content
- [ ] Confusing or misleading content
- [ ] Other

## Change suggestion

Maybe link to one of our own content, maybe a video like https://youtu.be/1PHZHpVPLk4

## More context

 see https://app.circleci.com/pipelines/github/ConsenSys/doc.teku/1868/workflows/313fa21a-617b-49a3-8016-00331ec0f2a9/jobs/4352?invite=true#step-106-86

**Comment by alexandratran** [comment]
Already fixed by #414
