### ISSUE TITLE
Unhide the doppelganger detection option

### ISSUE THREAD

**Issue by bgravenorst** [ConsenSys/doc.teku#433]
See: https://github.com/ConsenSys/teku/pull/6801

**Comment by rolfyone** [comment]
just be aware we're wanting to get a release out prior to making these options unhidden, so until 23.2.0 goes out, we need them to remain hidden...
this work was done, then reverted in https://github.com/ConsenSys/doc.teku/pull/432

**Comment by alexandratran** [comment]
fixed by #438
