### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by MadelineMurray** [Consensys/doc.teku#531]
On this page -> https://docs.teku.consensys.io/development/reference/cli#checkpoint-sync-url
This appears ->  URL of a Checkpointz endpoint

**Comment by joaniefromtheblock** [comment]
Working on this

**Comment by rolfyone** [comment]
Checkpointz refers to an actual product - the reason that was present so people would google that and find the product they're looking for 
https://github.com/ethpandaops/checkpointz

**Comment by rolfyone** [comment]
I've re-opened on the basis that this probably wasn't a change we should make...
