### ISSUE TITLE
Document adding `claimId` to the execution engine JWT payload 

### ISSUE THREAD

**Issue by mjsmike62** [Consensys/doc.teku#537]
Document that `claimId` can be set in a JWT payload to convey information about the client being authenticated. This is useful for more advanced forms of authentication beyond the basic 1-CL-to-1-EL authentication that's usually done.

Also, document that adding `claimId` to the JWT payload for the execution engine is tested with `ee-jwt-claim-id: foobar`.

See PR: [Add `id` claim to the execution engine JWT payload #7816](https://github.com/Consensys/teku/pull/7816)

**Comment by StefanBratanov** [comment]
Hi, this has been done as part of https://github.com/Consensys/doc.teku/pull/530
