### ISSUE TITLE
Document the validator slashing protection option (`--stop-vc-when-validator-slashed-enabled`)

### ISSUE THREAD

**Issue by mjsmike62** [Consensys/doc.teku#538]
Document the following:
Add the `--stop-vc-when-validator-slashed-enabled` option to enable VC shutdown when a validator gets slashed.

When using a remote BN, this option requires the BN to support the new `attester_slashing` and `proposer_slashing` SSE events.

To ensure BN backward compatibility, the VC subscribes to the `attester_slashing` and `proposer_slashing` SSE events only when the `--stop-vc-when-validator-slashed-enabled` option is enabled (in addition to the head events). Otherwise, the VC only subscribes to the head events.

See PR: [7707 validator slashing protection #7826](https://github.com/Consensys/teku/pull/7826)

**Comment by mehdi-aouadi** [comment]
Hi @mjsmike62, fyi there is already a draft PR for this. I'll convert it to ready for review when the feature is ready

**Comment by alexandratran** [comment]
fixed by #526
