### ISSUE TITLE
Add a subscribe link for releases to teku landing page, potentially also (X)twitter ref.

### ISSUE THREAD

**Issue by rolfyone** [Consensys/doc.teku#549]
ref. https://consensys.io/teku

just looking at removing a stale page, and one thing that it does seem to have is a `subscribe` that points to https://pages.consensys.net/teku-sign-up which allows signing up for release notifications.

It also has a link to follow on twitter https://twitter.com/teku_consensys and a different discord invite link (https://discord.gg/consensys) - Im not sure which is a better link for discord, just capturing here...

I think if we can add the release notification subscription and twitter reference, that the teku landing page on consensys.io is no longer required, and I can get that page removed (or redirect to docs) in preference to the docs landing page - I'm assuming these couple of things are fairly minor to accomplish?

**Comment by bgravenorst** [comment]
For the docs team:
- On the Teku landing page (and/or elsewhere, if more suitable), add a link to email list so that users can subscribe to Teku releases (https://share.hsforms.com/1bkXI6uLpSROGBRVig4KeIQ2urwb)
- Confirm that the Discord link is correct
- Add a Twitter(X) icon link to the top right of the landing page.

**Comment by m4sterbunny** [comment]
NB Twitter class is out of date (Birdie not X) -- I applied it anyway as per Besu docs --> we could fall in line and update both WDYT folks?

**Comment by m4sterbunny** [comment]
https://github.com/Consensys/doc.teku/pull/587

**Comment by m4sterbunny** [comment]
Interesting -- so twitter does offer light and dark mode logos as part of brand kit BUT not as svg: https://about.x.com/en/who-we-are/brand-toolkit >> https://about.x.com/content/dam/about-twitter/x/brand-toolkit/x-logo.zip

**Comment by m4sterbunny** [comment]
Interesting -- so twitter does offer light and dark mode logos as part of brand kit BUT not as svg: https://about.x.com/en/who-we-are/brand-toolkit >> https://about.x.com/content/dam/about-twitter/x/brand-toolkit/x-logo.zip
