### ISSUE TITLE
rename Hyperledger Besu to just Besu

### ISSUE THREAD

**Issue by macfarla** [Consensys/doc.teku#605]
### Where is the issue?

eg https://docs.teku.consensys.io/get-started/connect/mainnet

### Issue type

- [ ] Missing content
- [X] Outdated content
- [ ] Inaccurate content

### Description

find and replace "Hyperledger Besu" to "Besu"

**Comment by DrParadox05** [comment]
Can I work on this?

**Comment by macfarla** [comment]
go for it @DrParadox05
